### ISSUE TITLE
GPU initialization error 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [imatge-upc/activitynet-2016-cvprw#26]
Hi, I  am getting this error when I am running   run_all_pipeline.py file.    
I have changed my ~/.theanorc file according to given instructions for this project. 

(venv) asad@asad-Z370P-D3:~/activitynet-2016-cvprw$ python scripts/run_all_pipeline.py -i data/vid2.mp4
Using Theano backend.
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.dnn.NoCuDNNRaise object at 0x7fa416199510>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py", line 2564, in apply
    if not dnn_available():
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 322, in dnn_available
    v = dnn_version()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 412, in dnn_version
    profile=False)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1285, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1364, in cmodule_key_
    numpy.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fa415f21bd0>(), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

Traceback (most recent call last):
  File "scripts/run_all_pipeline.py", line 5, in <module>
    from keras.layers import (LSTM, BatchNormalization, Convolution3D, Dense, Dropout, Flatten, Input,
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import backend
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/home/asad/venv/local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 5, in <module>
    import theano
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1587, in cthunk_factory
    key = self.cmodule_key()
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1285, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/asad/venv/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1364, in cmodule_key_
    numpy.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

**Comment by albertomontesg** [comment]
Are you using the version specified in the `requirements.txt` file?

**Comment by MuhammadAsadJaved** [comment]
> Are you using the version specified in the `requirements.txt` file?

@albertomontesg  Yes I am  using same specified procedure and also requirements.

**Comment by MuhammadAsadJaved** [comment]
This error was due to some GPU problem.  I solved it after setting cnmem value from  1 to 0.8.

i.e  cnmem = 0.8  in ~/.theanorc file.
 
[global]
floatX = float32
device = gpu
optimizer_including = cudnn

[lib]
cnmem = 1

[dnn]
enabled = True
